sudo: false
language: ruby
script: script/ci.sh
cache: bundler
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2
