language: ruby
env: CUCUMBER_FORMAT=progress
bundler_args: --without extras
script: "bundle exec rake ci:build --trace"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
branches:
  only:
    - master
    - 1-x-stable
    - travis-testing

